name: Run Tests

on:
  pull_request:
  push:
    branches: 
      - '**'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Decode Firebase Key File
        run: |
          echo "${{ secrets.FIREBASE_KEY_FILE_BASE64 }}" | base64 --decode > firebase_key.json
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio httpx 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pytest
        run: pytest tests/
        env:
          FIREBASE_KEY_FILE: 'firebase_key.json'
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
          MAIL_FROM_NAME: ${{ secrets.MAIL_FROM_NAME }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}